version: '3'

services:
  psql:
    image: postgres:16
    container_name: psql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_ROOT_PASSWORD: ${PSQL_ROOT_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PSQL_USER} -d ${PSQL_DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  buytech:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: buytech
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8080"
    restart: always
    volumes:
      - .:/buyTech
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - psql
  
volumes:
  postgres_data: