# Generated by Django 4.1.7 on 2023-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('HP', 'HP'), ('Acer', 'Acer')], max_length=50)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('OnePlus', 'OnePlus'), ('Xiaomi', 'Xiaomi'), ('Google', 'Google')], max_length=50)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('os', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop')], default='Mobile', max_length=128, verbose_name='category')),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads/products/')),
            ],
        ),
    ]
