# Generated by Django 4.1.7 on 2023-03-28 06:01

from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_coupon_usage_limit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', home.models.CustomUserManager()),
            ],
        ),
    ]
