# Generated by Django 5.0.6 on 2024-06-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('Return', 'Return'), ('Exchange', 'Exchange')], max_length=20, null=True),
        ),
    ]
