# Generated by Django 5.0.6 on 2024-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_feedback_orderitem_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Return', 'Return'), ('Exchange', 'Exchange')], max_length=20, null=True),
        ),
    ]
